name = "EquationOfStateRecipes"
uuid = "8d49d7c9-511f-4c38-862f-eeb1232c8dad"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
