name = "EquationOfStateRecipes"
uuid = "8d49d7c9-511f-4c38-862f-eeb1232c8dad"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.4-DEV"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
EquationsOfStateOfSolids = "1eaa2786-f833-4167-8397-974edad0881e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Unitful = "0.18, 1"
julia = "1"
RecipesBase = "0.6, 0.7, 0.8, 1"
EquationsOfStateOfSolids = "0.1, 0.2, 0.3, 0.4"

[targets]
test = ["Test"]
